### PR TITLE
testimonial styles updated

### PR DESCRIPTION
**Pull request by Yash7818**
# Pull Request Template

Summarize what this PR fixes:-
This pull request added styles to the testimonial part mentioned as per the issue #655 

#### **Checklist**

(Add an `x` between the brackets to check the items)

- [x] I have summarize what this PR fixes above
- [x] I have provided the issue ID/URL above
- [x] I have not added Bootstrap or jQuery and used correct styling guide.
- [x] This PR fixes only the issue mentioned above (create separate PRs for separate issues)
- [x] I was the first one to claim the issue or I created the issue - I created the issue

### CODE REVIEW

**Comment by brittneypostma** [comment]
At desktop size and up it looks great, but at smaller breakpoints it starts to overflow and doesn't fit on the screen. 
image
image
image

**Comment by brittneypostma** [comment]
We may need to scrap the quote-box and just put a box shadow around the text. It should be a p tag and not an h3 with italic font-style.

**Comment by Yash7818** [comment]
so instead of using that quote box svg may i use simple div for this purpose @brittneypostma

**Comment by Yash7818** [comment]
on what screen size do you tried it @brittneypostma

**Pull request closed without merging**
