### PR TITLE
capitalize the letter s

### PR DESCRIPTION
**Pull request by GemzBond**
Change the placeholder of email from "Enter email" to "example@domain.com"

### CODE REVIEW

**Review by GemzBond — COMMENTED** [review]
Change the placeholder in email from "Enter email" to "example@domain.com"

**Review by GemzBond — COMMENTED** [review]
change placeholder email

**Review by GemzBond — COMMENTED** [review]
implement correct spacing

**Comment by brittneypostma** [comment]
There are conflicts with this pull request and just correcting spelling errors is not a quality pr unless it fixes something.

**Pull request closed without merging**
