### PR TITLE
add some style and changing the team names

### PR DESCRIPTION
**Pull request by RedSquirrrel**
# Pull Request Template

> Please provide all of the details below. Pull requests missing any of the information below will be closed!

**Sumarise what this PR fixes:** < added to toggle button cursor pointer, changing the team names, and h2 "Meet Our Team" added text shadow and font weight >

**Fixes #:** < Enter Issue ID/URL >

# Checklist:
(Add an `x` between the brackets to check the items)

- [x] I have sumarised what this PR fixes above
- [ ] I have provided the issue ID/URL above
- [ ] This PR fixes only the issue mentioned above (create seperate PRs for seperate issues)
- [ ] I was the first one to claim the issue or I created the issue

### CODE REVIEW

**Comment by RedSquirrrel** [comment]
Hello, 
I tried to follow the steps, I hope I did well. If i did something wrong, please let me know

**Comment by MattCSmith** [comment]
Hey @RedSquirrrel 
There is a conflict with this PR I am unable to resolve from my end. If you are able to resolve it that would be awesome. 
Also I'm not sure which [Issue Number](https://github.com/zero-to-mastery/Keiko-Corp/issues?page=2&q=is%3Aissue+is%3Aopen) this refers too. 

You can either provide the number or the URL, it just helps us as maintainers understand what the PR is resolving and ensure we keep the issues tab clean and tidy. 

Regards
Matt

**Comment by RedSquirrrel** [comment]
Hi Matt,
 So sorry for this conflict, as a  beginner 😕 , I hope it's okay now, if I haven't done something well, please let me know.
 Thank you, Anette

**Comment by MattCSmith** [comment]
> Hi Matt,
> So sorry for this conflict, as a beginner 😕 , I hope it's okay now, if I haven't done something well, please let me know.
> Thank you, Anette

Hey @RedSquirrrel 
No problem at all, conflicts are just the nature of Github, especially such a large project. Its good experience to be able to resolve them 🙂. 

I just realised this did not have an issue number attached. 
Any chance you can mark it as complete 🙂

**Pull request merged**
