### PR TITLE
my info to the contibutors.md file #814

### PR DESCRIPTION
**Pull request by WayneMacMavis**
# Pull Request Template

> Please provide all of the details below. Pull requests missing any of the information below will be closed!
> Providing the issue number/url helps us identify the problem being solved and keep the issues tab clean and tidy

#814

Summarize what this PR fixes:-

Fixes # It updates the contributors file with my details

#### **Checklist**

(Add an `x` between the brackets to check the items)

- [x ] I have summarize what this PR fixes above
- [x ] I have provided the issue ID/URL above
- [x ] I have not added Bootstrap or jQuery and used correct styling guide.
- [x ] This PR fixes only the issue mentioned above (create separate PRs for separate issues)
- [x ] I was the first one to claim the issue or I created the issue - I created the issue

### CODE REVIEW

**Comment by brittneypostma** [comment]
I will be happy to merge this if you can provide me with previous issues you've resolved. It is against hacktoberfest policy to just add your name to contributors, so I need to see previous work done.

**Comment by WayneMacMavis** [comment]
@brittneypostma Ok i understand. I just done some small fixes like the button colors when hovering and the darkmode toggle button when it was broken. But it's not super crucial that i be added to the contributors list. Just thought it was a simple thing because i did contribute. So no worries

**Comment by brittneypostma** [comment]
Ok, I just need to check them. I can merge it in.

**Comment by WayneMacMavis** [comment]
Thank you @brittneypostma, It is much appreciated. Boy! they are strict this year. Last year it was quite easy to do. This year not so much. I guess they want people to actually work for it.

**Pull request merged**
