### PR TITLE
Changed Header style to meet styling from mockup

### PR DESCRIPTION
**Pull request by batistaDev1113**
# Pull Request Template

> Please provide all of the details below. Pull requests missing any of the information below will be closed!
1. - I replaced the styling and layout for the header on index.html
2. - Also replaced tab on nav mistakenly going to pricing rather than Team

##Please see the screenshot attached below for the final result

> Providing the issue number/url helps us identify the problem being solved and keep the issues tab clean and tidy
This PR fixes issues with header styling to match mockup from issue #360 
header-style

Summarize what this PR fixes:-

Fixes #

#### **Checklist**

(Add an `x` between the brackets to check the items)

- [x] I have summarize what this PR fixes above
- [x] I have provided the issue ID/URL above
- [x] I have not added Bootstrap or jQuery and used correct styling guide.
- [x] This PR fixes only the issue mentioned above (create separate PRs for separate issues)
- [x] I was the first one to claim the issue or I created the issue - I created the issue

** I was not really the first one to claim this issue but was assigned to it by @brittneypostma.  I am just checking the box to avoid the PR from being closed.

### CODE REVIEW

**Comment by batistaDev1113** [comment]
@brittneypostma Could you please take a look at this conflict?

Thank you!

**Comment by batistaDev1113** [comment]
@brittneypostma 
I fixed the conflict.  Please check the PR and let me know if you have any questions.

Thank you

**Comment by brittneypostma** [comment]
This looks like a great first step, there is a background on the links and contact button that isn't aligning, but i'll make a new issue after we get some others cleared out.

**Comment by batistaDev1113** [comment]
Got it!  Thank you!

**Pull request merged**
