### PR TITLE
Fixing Social Media Icons

### LINKED ISSUE #219: [FIX] Fixing Social Media Icons
There are two rows of social media icons. Second row has extra space between the icons. I'm Working on it.

### PR DESCRIPTION
**Pull request by dpcoolmufa**
# Pull Request Template

> Please provide all of the details below. Pull requests missing any of the information below will be closed!
> Providing the issue number/url helps us identify the problem being solved and keep the issues tab clean and tidy

#### **What issue does this fix?**

Summarize what this PR fixes:-
The Social Media Icons where not visible when changed to dark mode. This PR fixes that issue. 

#### **What issue is it attached to?**

Fixes #219 

#### **Checklist**

(Add an `x` between the brackets to check the items)

- [x ] I have summarize what this PR fixes above
- [ x] I have provided the issue ID/URL above
- [ x] I have not added Bootstrap or jQuery and used correct styling guide.
- [ x] This PR fixes only the issue mentioned above (create separate PRs for separate issues)
- [ x] I was the first one to claim the issue or I created the issue

### CODE REVIEW

**Comment by akshatz** [comment]
Even in light mode it Social Media icons are jumping...

**Comment by akshatz** [comment]
I can fix those.

**Comment by brittneypostma** [comment]
This is an older issue and the styles are not consistent with the new mockup. Try creating a new issue if the problem still occurs and resubmit.

**Comment by AmrutaKoshe** [comment]
> This is an older issue and the styles are not consistent with the new mockup. Try creating a new issue if the problem still occurs and resubmit.

Can you tell me where I can find the new mockup?

**Pull request closed without merging**
