### PR TITLE
Fixing Social Media Icons Section

### PR DESCRIPTION
**Pull request by dpcoolmufa**
# Pull Request Template

> Please provide all of the details below. Pull requests missing any of the information below will be closed!

**Sumarise what this PR fixes:** 
I have Modified index.html and Styles.css to implement the Fix. It includes Deleting one of the Social Media icons row and Commented out lines 323 to 325 in Styles.css

**Fixes #:** 219

# Checklist:

(Add an `x` between the brackets to check the items)

- [x ] I have sumarised what this PR fixes above
- [ x] I have provided the issue ID/URL above
- [x ] This PR fixes only the issue mentioned above (create seperate PRs for seperate issues)
- [ x] I was the first one to claim the issue or I created the issue

### CODE REVIEW

**Comment by abdus** [comment]
Hey, looks like this is an empty PR (meaning, it introduces no changes to the existing codebase). 
Thanks for putting efforts on making this PR anyways :)

**Comment by dpcoolmufa** [comment]
But i made the changes


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
10/02/20,
11:21:32 PM

**Comment by abdus** [comment]
the changes you've made are probably already merged into this repository. so, it's empty

**Comment by dpcoolmufa** [comment]
okay,thank you.




[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
10/03/20,
09:17:12 AM

**Pull request closed without merging**
