### PR TITLE
Renovated the website

### PR DESCRIPTION
**Pull request by vivekboss99**
# Pull Request Template

> Please provide all of the details below. Pull requests missing any of the information below will be closed!
> Providing the issue number/url helps us identify the problem being solved and keep the issues tab clean and tidy

#### **Sumarise what this PR fixes**
-Before the buttons which used to take the user to the specific part of the page were not working, i fixed those issues.
-Added Contact,Blog and About buttons at the bottom of home page.
-There was no back or home button for contact and about pages, i added a new home button which is free to use.
-Feature 1's and Feature 3's 'learn more' hyperlink was not working, i fixed it.
-Finally i removed redundant elements from the website like double times use of company icons and social media handles.
<Detail what your PR changes/fixes>

#### **What [ISSUE NUMBER](https://github.com/zero-to-mastery/Keiko-Corp/issues) does this fix?**

Fixes #<enter number>

#### Checklist:

(Add an `x` between the brackets to check the items)

- [x] I have sumarised what this PR fixes above
- [ ] I have provided the issue ID/URL above
- [x] This PR fixes only the issue mentioned above (create seperate PRs for seperate issues)
- [x] I was the first one to claim the issue or I created the issue

### CODE REVIEW

**Comment by vivekboss99** [comment]
if i messed up something please correct me, this is my first time doing this kind of stuff.I tried to change stuff which needed to me changed or fixed, i came directly from the middle of the Zero to Mastery course(still learning)

**Comment by MattCSmith** [comment]
Hey @vivekboss99
There is a merge conflict, this usually (and in this case) means there have been changes to the repo since you pull down your clone. 
You need to run `git pull origin master` assuming that you followed the steps to set the upstream as mentioned in the readme. 

Reach out on Discord if you get stuck.

**Comment by MattCSmith** [comment]
Also you did not specify which Issue ID this pull request fixes, if you could include that info, that would be awesome 🙂

**Comment by vivekboss99** [comment]
@MattCSmith , i tried to resolve those issues and followed the instructions to setup upstream , it was really confusing when i was resolving the conflicts i might have done some mistakes and i solved some problems in the website like button finctionality and removal of redundant elements and those problems where not mentioned in the issues so, i made changes and made pull request.
Please guide me if i made any mistakes.

**Comment by brittneypostma** [comment]
@vivekboss99 there are too many conflicts still to resolve. I am going to close this pr. I would keep your local copy as a reference and try to start with a fresh clone tomorrow to add your code back in to, then resubmit the pr.

**Pull request closed without merging**
