### PR TITLE
Linking on Logo Icon has been added

### LINKED ISSUE #562: Logo needs to have a link to home page
# New Mockup

Please check `assets/css/global.css`, design-assets folder images, and [figma files](https://www.figma.com/file/NY0Do1PFf4xl0ZuSTA1X9U/Keiko-Corp-Hacktoberfest-Project?node-id=2%3A10) for updated style guides. Any new pull request should use the updated color, spacing, and sizing variables.

## No Bootstrap or jQuery

Please refrain from adding Bootstrap or jQuery to the site. These pr's will be closed. They overwrite global styles. Vanilla CSS and JS is way better now anyways 😊

# New Task:

[//]: # 'Please use this template when creating new tasks, issues not using this template will be closed'

#### What is the task

Page logo does not have a linking to home page.

### Who is the task for?

[//]: # 'Place and x in between the brackets to check'

- [x] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [x] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

### PR DESCRIPTION
**Pull request by Krungleviciute**
# Pull Request Template

> Please provide all of the details below. Pull requests missing any of the information below will be closed!
> Providing the issue number/url helps us identify the problem being solved and keep the issues tab clean and tidy

Summarize what this PR fixes:- 
this PR was created to add linking on logo icon to be redirected to home page.

Link to issues https://github.com/zero-to-mastery/Keiko-Corp/issues/562
Fixes #562

#### **Checklist**

(Add an `x` between the brackets to check the items)

- [x] I have summarize what this PR fixes above
- [x] I have provided the issue ID/URL above
- [x] I have not added Bootstrap or jQuery and used correct styling guide.
- [x] This PR fixes only the issue mentioned above (create separate PRs for separate issues)
- [x] I was the first one to claim the issue or I created the issue - I created the issue

### CODE REVIEW

**Comment by brittneypostma** [comment]
This would be a fine change, but there are 4 files changed with a lot of formatting issues. Try resubmitting with just the link change.

**Comment by Krungleviciute** [comment]
> This would be a fine change, but there are 4 files changed with a lot of formatting issues. Try resubmitting with just the link change.
4 files were changed because there is different html files that needs to be updated accordingly. 
Should I create a new issue now?

**Comment by brittneypostma** [comment]
@Krungleviciute, this issue is only for Linking on Logo, so if a pr is linked to it, that's all it should change. Any other changes would need a new issue, but make sure its not already covered in the issues currently.

**Comment by Krungleviciute** [comment]
> @Krungleviciute, this issue is only for Linking on Logo, so if a pr is linked to it, that's all it should change. Any other changes would need a new issue, but make sure its not already covered in the issues currently.

Ok, I don't know where the problem was... Do I have to create new issue for different html files just to add linking?? But it is the same problem..

**Pull request closed without merging**
